spring.application.name=planit
spring.config.import=optional:file:.env[.properties]

# === Configuration de la base de données PostgreSQL ===
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/descodeuses}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# === Configuration JPA / Hibernate ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# automatiquement modifier les tables à chaque démarrage, sans supprimer les données
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB:mydb}

jwt.secret=${JWT_SECRET}
allowCorsOrigin=${CORS_ORIGIN:http://localhost:4200}
